{
 "title": "Gin Application Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (code) (gin_uri_request_total{code!~\"2.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gin_uri_request_total{code!~\"2.*\"}) / sum(gin_uri_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total[5m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(process_network_transmit_bytes_total[5m])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum (rate(gin_request_duration_bucket[5m])) by (le, instance))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Number of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "gin_request_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "URI Request",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (gin_uri_request_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Method",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (gin_uri_request_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (gin_uri_request_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}